function [fitresult, gof] = createFit(v2_cases, P2_cases)
%CREATEFIT(V2_CASES,P2_CASES)
%  Create a fit.
%
%  Data for 'Fitting Force-Velocity Data' fit:
%      X Input : v2_cases
%      Y Output: P2_cases
%  Output:                                        
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Feb-2021 18:40:25


%% Fit: 'Fitting Force-Velocity Data'.
[xData, yData] = prepareCurveData( v2_cases, P2_cases );

% Set up fittype and options.
ft = fittype( '((b * P_0) - (v*a))/(v + b)', 'independent', 'v', 'dependent', 'p' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.792207329559554 0.959492426392903 0.655740699156587];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fitting Force-Velocity Data' );
h = plot( fitresult, xData, yData );
legend( h, 'P2_cases vs. v2_cases', 'Fitting Force-Velocity Data', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'v2_cases', 'Interpreter', 'none' );
ylabel( 'P2_cases', 'Interpreter', 'none' );
grid on


